//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RzszyyyRepo.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RzszyyyRepo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap icon_print {
            get {
                object obj = ResourceManager.GetObject("icon-print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Network2_32x32 {
            get {
                object obj = ResourceManager.GetObject("Network2-32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_001 {
            get {
                object obj = ResourceManager.GetObject("Shell32 001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_002 {
            get {
                object obj = ResourceManager.GetObject("Shell32 002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_004 {
            get {
                object obj = ResourceManager.GetObject("Shell32 004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_005 {
            get {
                object obj = ResourceManager.GetObject("Shell32 005", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_010 {
            get {
                object obj = ResourceManager.GetObject("Shell32 010", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_011 {
            get {
                object obj = ResourceManager.GetObject("Shell32 011", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_014 {
            get {
                object obj = ResourceManager.GetObject("Shell32 014", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_016 {
            get {
                object obj = ResourceManager.GetObject("Shell32 016", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_017 {
            get {
                object obj = ResourceManager.GetObject("Shell32 017", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_018 {
            get {
                object obj = ResourceManager.GetObject("Shell32 018", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_019 {
            get {
                object obj = ResourceManager.GetObject("Shell32 019", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_020 {
            get {
                object obj = ResourceManager.GetObject("Shell32 020", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_021 {
            get {
                object obj = ResourceManager.GetObject("Shell32 021", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_022 {
            get {
                object obj = ResourceManager.GetObject("Shell32 022", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_023 {
            get {
                object obj = ResourceManager.GetObject("Shell32 023", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_028 {
            get {
                object obj = ResourceManager.GetObject("Shell32 028", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_035 {
            get {
                object obj = ResourceManager.GetObject("Shell32 035", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_046 {
            get {
                object obj = ResourceManager.GetObject("Shell32 046", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_047 {
            get {
                object obj = ResourceManager.GetObject("Shell32 047", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_048 {
            get {
                object obj = ResourceManager.GetObject("Shell32 048", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_056 {
            get {
                object obj = ResourceManager.GetObject("Shell32 056", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_061 {
            get {
                object obj = ResourceManager.GetObject("Shell32 061", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_082 {
            get {
                object obj = ResourceManager.GetObject("Shell32 082", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_083 {
            get {
                object obj = ResourceManager.GetObject("Shell32 083", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_086 {
            get {
                object obj = ResourceManager.GetObject("Shell32 086", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_104 {
            get {
                object obj = ResourceManager.GetObject("Shell32 104", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_110 {
            get {
                object obj = ResourceManager.GetObject("Shell32 110", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_112 {
            get {
                object obj = ResourceManager.GetObject("Shell32 112", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_127 {
            get {
                object obj = ResourceManager.GetObject("Shell32 127", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_128 {
            get {
                object obj = ResourceManager.GetObject("Shell32 128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_129 {
            get {
                object obj = ResourceManager.GetObject("Shell32 129", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_130 {
            get {
                object obj = ResourceManager.GetObject("Shell32 130", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_131 {
            get {
                object obj = ResourceManager.GetObject("Shell32 131", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_132 {
            get {
                object obj = ResourceManager.GetObject("Shell32 132", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_149 {
            get {
                object obj = ResourceManager.GetObject("Shell32 149", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_150 {
            get {
                object obj = ResourceManager.GetObject("Shell32 150", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_151 {
            get {
                object obj = ResourceManager.GetObject("Shell32 151", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_159 {
            get {
                object obj = ResourceManager.GetObject("Shell32 159", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_161 {
            get {
                object obj = ResourceManager.GetObject("Shell32 161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_165 {
            get {
                object obj = ResourceManager.GetObject("Shell32 165", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_206 {
            get {
                object obj = ResourceManager.GetObject("Shell32 206", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_220 {
            get {
                object obj = ResourceManager.GetObject("Shell32 220", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell32_221 {
            get {
                object obj = ResourceManager.GetObject("Shell32 221", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap word_2003_32x32 {
            get {
                object obj = ResourceManager.GetObject("word 2003-32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap word遇到问题需要关闭 {
            get {
                object obj = ResourceManager.GetObject("word遇到问题需要关闭", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 风眼ico {
            get {
                object obj = ResourceManager.GetObject("风眼ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
